version: '3.8'

services:
  app:
    build:
      context: .
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOSTNAME: ${DB_HOSTNAME}
        DB_NAME: ${DB_NAME}
        JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./.env:/app/.env
