name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.1

      - name: Run tests with coverage
        run: |
          go test ./... -coverprofile=coverage.out
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
            file: coverage.out
            flags: unittests
            name: codecov-umbrella
            fail_ci_if_error: true
            token: ${{ secrets.CODECOV_TOKEN }}
